<template>
  <div class="FieldIcon">
    <svg
      width="14px"
      height="14px"
      viewBox="0 0 14 14"
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
    >
      <defs>
        <rect id="path-1" x="0" y="0" width="14" height="14"></rect>
      </defs>
      <g
        id="数据分析平台"
        stroke="none"
        stroke-width="1"
        fill="none"
        fill-rule="evenodd"
      >
        <g id="组件库" transform="translate(-598.000000, -523.000000)">
          <g
            id="btn-展示字段-normal"
            transform="translate(598.000000, 523.000000)"
          >
            <mask id="mask-2" fill="white">
              <use xlink:href="#path-1"></use>
            </mask>
            <use
              id="Mask"
              fill-opacity="0"
              fill="#D8D8D8"
              xlink:href="#path-1"
            ></use>
            <rect
              id="Rectangle"
              stroke="currentColor"
              mask="url(#mask-2)"
              x="0.5"
              y="0.5"
              width="13"
              height="13"
              rx="2"
            ></rect>
            <rect
              id="Rectangle"
              fill="currentColor"
              mask="url(#mask-2)"
              x="2"
              y="3"
              width="5"
              height="1"
              rx="0.5"
            ></rect>
            <rect
              id="Rectangle-Copy-17"
              fill="currentColor"
              mask="url(#mask-2)"
              x="8"
              y="3"
              width="4"
              height="1"
              rx="0.5"
            ></rect>
            <rect
              id="Rectangle-Copy-20"
              fill="currentColor"
              mask="url(#mask-2)"
              x="8"
              y="5"
              width="4"
              height="1"
              rx="0.5"
            ></rect>
            <rect
              id="Rectangle-Copy-21"
              fill="currentColor"
              mask="url(#mask-2)"
              x="8"
              y="7"
              width="4"
              height="1"
              rx="0.5"
            ></rect>
            <rect
              id="Rectangle-Copy-16"
              fill="currentColor"
              mask="url(#mask-2)"
              x="2"
              y="10"
              width="10"
              height="1"
              rx="0.5"
            ></rect>
            <rect
              id="Rectangle"
              fill="currentColor"
              mask="url(#mask-2)"
              x="4"
              y="3"
              width="1"
              height="5"
              rx="0.5"
            ></rect>
          </g>
        </g>
      </g>
    </svg>
  </div>
</template>
<script>
export default {
  name: "FieldIcon"
}
</script>
